<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/08/20 22:28:00

return array(
'propel' => new sfPropelDatabase(array (
  'dsn' => 'mysql:dbname=jc_test;host=localhost',
  'username' => 'root',
  'password' => NULL,
  'encoding' => 'utf8',
  'name' => 'propel',
)),);
