<?php

/**
 * Skeleton subclass for performing query and update operations on the 'product_has_sale' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 08/20/15 23:01:48
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ProductHasSalePeer extends BaseProductHasSalePeer {
    /*
     * метод выбирает необходимую информацию по айди продукта
     */

    static function getSalesByProductId($productID) {
        $stm  = Propel::getConnection()->prepare('
            SELECT 
                s.`id`, s.`title`, s.`content`
              FROM
                product_has_sale AS ps
                INNER JOIN sale AS s
                  ON s.id = ps.sale_id 
              WHERE ps.product_id = :id 
        ');
        $stm->bindParam(':id', $productID);
        $stm->execute();
        $sales = $stm->fetchAll(PDO::FETCH_ASSOC);
        return $sales;
    }

}

// ProductHasSalePeer
