<?php

/**
 * Skeleton subclass for performing query and update operations on the 'product_has_product_category' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 08/20/15 22:13:12
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ProductHasProductCategoryPeer extends BaseProductHasProductCategoryPeer {
    /*
     * метод выбирает необходимую информацию по айди продукта
     */
    static function getCategoriesByProductId($productID) {
        $stm             = Propel::getConnection()->prepare('
            SELECT 
                cat.`id`, cat.`parent_id`, cat.`title`
              FROM
                product_has_product_category AS pcat
                INNER JOIN product_category AS cat
                  ON cat.id = pcat.product_category_id 
              WHERE pcat.product_id = :id 
        ');
        $stm->bindParam(':id', $productID);
        $stm->execute();
        $cats = $stm->fetchAll(PDO::FETCH_ASSOC);
        return $cats;
    }

}

// ProductHasProductCategoryPeer
