<?php


/**
 * Skeleton subclass for performing query and update operations on the 'product_has_photo' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 08/20/15 22:13:11
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ProductHasPhotoPeer extends BaseProductHasPhotoPeer {
    /*
     * метод выбирает необходимую информацию по айди продукта
     */

    static function getPhotosByProductId($productID) {
        $stm  = Propel::getConnection()->prepare('
            SELECT 
                p.`id`, p.`title`, p.`content`
              FROM
                product_has_photo AS pp
                INNER JOIN photo AS p
                  ON p.id = pp.photo_id 
              WHERE pp.product_id = :id 
        ');
        $stm->bindParam(':id', $productID);
        $stm->execute();
        $sales = $stm->fetchAll(PDO::FETCH_ASSOC);
        return $sales;
    }


} // ProductHasPhotoPeer
