<?php

/**
 * Skeleton subclass for performing query and update operations on the 'product' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 08/20/15 22:13:11
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ProductPeer extends BaseProductPeer {

    //метод агрегирует действия для создания объекта содержащего всю информацию о продукте
    public static function getProductDetails($productID) {

        
        /* наша информация о продукте будет собрана в асоциативный массив и будет включать:
         * 1. id нашего продукта ;
         * 2. заголвок нашего продукта ;
         * 3. описание нашего продукта ;
         * 4. id  и название категорий, куда входит наш продукт ;
         * 5. id, заголовки и описание скидок, которые имеет наш продукт ;
         * 6. id и заголовки фото, которые имеет наш продукт ;
         */
        
        //сначала получаем объект нашего продукта что даст возможность получить остальную информацию
        $productInfo = self::retrieveByPK($productID);
        
        //далее получаем масив информации о его категориях
        $categories = ProductHasProductCategoryPeer::getCategoriesByProductId($productID);
        
        //массив информации о скидках которые существуют
        $sales = ProductHasSalePeer::getSalesByProductId($productID);
        //информация о фото
        $photos = ProductHasPhotoPeer::getPhotosByProductId($productID);
        
        // формируем массив и возвращем его
        $productDetails = array(
            "id"          => $productInfo->getID(),
            "title"       => $productInfo->getTitle(),
            "description" => $productInfo->getDescription(),
            "categories"   => $categories,
            "sales"   => $sales,
            "photos"   => $photos,
        );
        return $productDetails;
    }

}

// ProductPeer
