<?php


/**
 * This class defines the structure of the 'product_category' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 08/20/15 23:01:48
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class ProductCategoryTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.ProductCategoryTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('product_category');
		$this->setPhpName('ProductCategory');
		$this->setClassname('ProductCategory');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, 11, null);
		$this->addForeignKey('PARENT_ID', 'ParentId', 'INTEGER', 'product_category', 'ID', false, 11, null);
		$this->addColumn('TITLE', 'Title', 'VARCHAR', true, 255, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('ProductCategoryRelatedByParentId', 'ProductCategory', RelationMap::MANY_TO_ONE, array('parent_id' => 'id', ), 'RESTRICT', 'CASCADE');
    $this->addRelation('ProductCategoryRelatedByParentId', 'ProductCategory', RelationMap::ONE_TO_MANY, array('id' => 'parent_id', ), 'RESTRICT', 'CASCADE');
    $this->addRelation('ProductHasProductCategory', 'ProductHasProductCategory', RelationMap::ONE_TO_MANY, array('id' => 'product_category_id', ), 'RESTRICT', 'CASCADE');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // ProductCategoryTableMap
